site_name: lexmachina-agent
repo_url: https://github.com/LexMachinaInc/lexmachina-agent
site_url: https://LexMachinaInc.github.io/lexmachina-agent
site_description: A2A agent for Lex Machina
site_author: Gavin Carothers for LexisNexis
edit_uri: edit/main/docs/
repo_name: LexMachinaInc/lexmachina-agent
copyright: Copyright © 2025 LexisNexis

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["src/lexmachina_agent"]
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/LexMachinaInc/lexmachina-agent
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/lexmachina-agent

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
